version: '3.7'
services:
    frontend:
        container_name: qiibee
        build: ./
        volumes:
            - './:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
