import fb from "../assets/images/fb.png";
import fyipe from "../assets/images/fyipe.jpeg";
import coca from "../assets/images/coca-cola.jpeg";
import img from "../assets/images/profile.png";
const brands = [
  {
    id: 1,
    name: "Coca-Cola",
    symbol: "CO",
    loyalty: 2342,
    role: "brand",
    image: coca,
    users: [1, 3, 4, 6, 7],
  },
  {
    id: 2,
    name: "Facebook",
    symbol: "FB",
    loyalty: 2532,
    role: "brand",
    image: fb,
    users: [1, 3, 5, 8],
  },
  {
    id: 3,
    name: "Fyipe",
    symbol: "FI",
    loyalty: 5345,
    role: "brand",
    image: fyipe,
    users: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    id: 4,
    name: "Netflix",
    symbol: "N",
    loyalty: 57353,
    role: "brand",
    image: fb,
    users: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    id: 5,
    name: "Krealax",
    symbol: "Kr",
    role: "brand",
    loyalty: 4563,
    image: [8, 7, 6, 5, 4, 2, 1],
  },
  {
    id: 6,
    name: "Barcelona",
    symbol: "Fcb",
    loyalty: 24653,
    image: fyipe,
    role: "brand",
    users: [1, 2, 8, 4, 5, 7],
  },
];

const users = [
  {
    id: 1,
    name: "Courage osemwengie",
    email: "courageosemwengie@gmail.com",
    loyalty: 2342,
    image: img,
    password: 123456,
    role: "user",
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
    ],
  },
  {
    id: 2,
    name: "Faith aigbokhan",
    email: "faith@gmail.com",
    loyalty: 2342,
    image: fyipe,
    password: 123456,
    role: "user",
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
    ],
  },
  {
    id: 3,
    name: "Faith aigbokhan",
    email: "faith@gmail.com",
    loyalty: 2342,
    image: img,
    password: 123456,
    role: "user",
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
    ],
  },
  {
    id: 4,
    name: "Faith aigbokhan",
    email: "faith@gmail.com",
    loyalty: 2342,
    image: fyipe,
    role: "user",
    password: 123456,
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
    ],
  },
  {
    id: 5,
    name: "Faith aigbokhan",
    email: "faith@gmail.com",
    loyalty: 2342,
    image: fyipe,
    role: "user",
    password: 123456,
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
      { id: 5, name: "Krealax", symbol: "Kr", loyalty: 4563, image: coca },
      { id: 6, name: "Barcelona", symbol: "Fcb", loyalty: 24653, image: fyipe },
    ],
  },
  {
    id: 6,
    name: "Courage osemwengie",
    email: "courageosemwengie@gmail.com",
    loyalty: 2342,
    password: 123456,
    role: "user",
    image: img,
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { id: 5, name: "Krealax", symbol: "Kr", loyalty: 4563, image: coca },
      { id: 6, name: "Barcelona", symbol: "Fcb", loyalty: 24653, image: fyipe },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
      { id: 5, name: "Krealax", symbol: "Kr", loyalty: 4563, image: coca },
      { id: 6, name: "Barcelona", symbol: "Fcb", loyalty: 24653, image: fyipe },
    ],
  },
  {
    id: 7,
    name: "Courage osemwengie",
    email: "courageosemwengie@gmail.com",
    loyalty: 2342,
    image: img,
    password: 123456,
    role: "user",
    brands: [
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
    ],
  },
  {
    id: 8,
    name: "Faith aigbokhan",
    email: "faith@gmail.com",
    loyalty: 2342,
    image: fyipe,
    role: "user",
    password: 123456,
    brands: [
      { name: "Facebook", symbol: "FB", loyalty: 2532, image: fb, id: 2 },
      { name: "Coca-Cola", symbol: "CO", loyalty: 2342, image: coca, id: 1 },
      { name: "Fyipe", symbol: "FI", loyalty: 5345, image: fyipe, id: 3 },
      { name: "Netflix", symbol: "N", loyalty: 57353, image: fb, id: 4 },
    ],
  },
];
export { brands, users };
