export const GET_BRAND_REQUEST = 'GET_BRAND_REQUEST';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAILURE = 'GET_BRAND_FAILURE';

//follow brand
export const FOLLOW_BRAND_REQUEST = 'FOLLOW_BRAND_REQUEST';
export const FOLLOW_BRAND_SUCCESS = 'FOLLOW_BRAND_SUCCESS';
export const FOLLOW_BRAND_FAILURE = 'FOLLOW_BRAND_FAILURE';
