//register user
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

//login user
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

//get User
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

//redeem user loyalty
export const REDEEM_LOYALTY_REQUEST = "REDEEM_LOYALTY_REQUEST";
export const REDEEM_LOYALTY_SUCCESS = "REDEEM_LOYALTY_SUCCESS";
export const REDEEM_LOYALTY_FAILURE = "REDEEM_LOYALTY_FAILURE";
